### ISSUE TITLE
Klasyczek - czy to miało tak wyglądać?

### ISSUE THREAD

**Issue by F4rra** [Alotech-cansat/alotech-website#2]
tak stronka wygląda na ekranie 2.8k, 16:10
tj. połowę napisu widać
![image_2023-10-23_111450290](https://github.com/Stanleeeeey/alotech/assets/148758971/6f923004-237d-4167-854a-d230aba9d2e0)

**Comment by Stanleeeeey** [comment]
jakies sugestie co do lepszego koloru?

**Comment by Stanleeeeey** [comment]
okej napis teraz nie nachodzi na logo, więc nie ma problemu z kolorystyką

**Comment by NixerDex** [comment]
huh
